---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    #this action logs in to dockerhub
      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # this action checks our code out inside the github actions job; this doesnt happen by default inside the job we are running. In our case, we need to access the code by we need to run tests and linting
      # on the code.
      - name: Checkout
        uses: actions/checkout@v2
      # this action runs the unit tests (you can copy it and run it on the termninal in the root directory and see what happens). Additional logic: before we run the tests, we need to run wait_for_db bc the
      # depend on the DB being available.
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # this action runs the linting (again, you can try it in the terminal)
      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"
        